export const normalWords = [
  'CAT', 'DOG', 'RUN', 'FLY', 'JUMP', 'CODE', 'FIRE', 'GAME',
  'TYPE', 'FAST', 'GLOW', 'NEON', 'BOMB', 'DARK', 'KEYS', 'PUSH',
  'BYTE', 'CYAN', 'VOID', 'HACK', 'RUST', 'NODE', 'LOOP', 'SORT',
  'LIST', 'FILE', 'PORT', 'GRID', 'LINK', 'FONT', 'CORE', 'EDIT',
  'VIEW', 'STAR', 'SHIP', 'BOLT', 'SNOW', 'WAVE', 'LOCK', 'FLAG',
  'SCAN', 'LOAD', 'DASH', 'RING', 'FRAG', 'SLIM', 'BEAM', 'FLUX',
  'APEX', 'DUSK', 'WARP', 'GRIT', 'BLIP', 'FADE', 'ZEAL', 'CRYPT',
  'BLAZE', 'CLASH', 'GLIDE', 'SURGE', 'PULSE', 'SWIFT', 'FROST',
  'SPARK', 'GHOST', 'STORM', 'BLADE', 'PHASE', 'DRIFT', 'ORBIT',
];

export const expertWords = [
  'PYTHON', 'ROCKET', 'DRAGON', 'TYPING', 'GALAXY', 'MASTER',
  'VECTOR', 'MATRIX', 'BRIDGE', 'PLANET', 'SYSTEM', 'FROZEN',
  'STREAM', 'BINARY', 'SIGNAL', 'CIPHER', 'CHROME', 'SCRIPT',
  'PLAYER', 'SHADOW', 'TURBO', 'NEBULA', 'LAUNCH', 'PORTAL',
  'QUANTUM', 'BLAZING', 'COMMAND', 'NETWORK', 'PHANTOM', 'THUNDER',
  'CRYSTAL', 'STATION', 'PROTOCOL', 'FRACTURE', 'TERMINAL',
  'OVERRIDE', 'COMPILED', 'SEQUENCE', 'VELOCITY', 'INTERFACE',
  'FREQUENCY', 'DIMENSION', 'ALGORITHM', 'SYNTHETIC', 'ENCRYPTED',
  'MAINFRAME', 'HYPERLINK', 'PROCESSOR', 'BANDWIDTH', 'CODEBREAK',
];
